function display_basevector(current_axes, origin, basevector, scale, tag)

basevector = basevector*scale;
    
delete(findobj('Tag', tag));

plot3(current_axes, 0,0,0, 'ok', 'MarkerFaceColor', 'black', 'Tag', tag);
quiver3( current_axes, ...
         origin(1), origin(2), origin(3), ...
         basevector(1,1), basevector(2,1), basevector(3,1), ...
         'LineWidth', 1, 'Color', 'red', 'Tag', tag);
     
quiver3( current_axes, ...
         origin(1), origin(2), origin(3), ...
         basevector(1,2), basevector(2,2), basevector(3,2), ...
         'LineWidth', 1, 'Color', 'green', 'Tag', tag);
     
quiver3( current_axes, ...
         origin(1), origin(2), origin(3), ...
         basevector(1,3), basevector(2,3), basevector(3,3), ...
         'LineWidth', 1, 'Color', 'blue', 'Tag', tag);
    
end

